simulation/diffusion.py
simulation/state.py

This adds a diffusion operator (with implicit time stepping) similar to the one [defined in the old framework](https://github.com/NutritionalLungImmunity/invasive-aspergillosis/blob/master/Diffusion/src/main/java/edu/uchc/Diffusion/Diffusion.java) except it uses GMRES rather than conjugate gradient as a solver.

Add an implicit diffusion solver as a utility method

---

Pipfile.lock
setup.py
simulation/cell.py
simulation/coordinates.py
simulation/module.py
simulation/modules/afumigatus.py
simulation/state.py
test/conftest.py
test/test_afumigatus.py
test/test_cell.py

@jmasison01 
This implements some approximation of #15 using a slightly different approach.  I'm not yet sure if this is the best way to model the data or not.  For one, it may rely on too much numpy black magic to be comprehensible.  We will have to experiment a little to see if it will work.
These are the important details:
1. The primary data structure is called `CellTree`, but it is actually just a flat list of cells.  It will allow fast serialization and vectorized operations on independent cells.  Assuming the boolean network updates don't depend on each other, this will accelerate the simulation significantly.
2. There is no representation of the topology of the trees (e.g. the parent and children relationships).  There didn't seem to be any clear need given the logic of the …

Implement a cell tree using numpy record arrays

---

simulation/cell.py
simulation/module.py
simulation/modules/afumigatus.py
simulation/state.py
test/conftest.py
test/test_afumigatus.py
test/test_cell.py

This is a largish refactor, so I'm giving some heads up.  I still need to add testing to make sure it's actually working and some docstrings.
The upshot is that the generic user-level cell class is now `CellList`.  The `CellTree` specific logic is moved to the afumigatus module.

Move tree logic to afumigatus module

---

simulation/cell.py
simulation/modules/afumigatus.py
test/test_cell.py

This also changes the API on the base `CellData` class so that changes can be made in the future without having to be propagated to subclasses.

Add `dead` to the list of default cell attributes

---

simulation/cell.py
simulation/coordinates.py
simulation/state.py
test/conftest.py
test/test_cell.py

This index allows efficient lookup for cells that exist inside a single voxel.  This also adds a simple API for listing cells inside a voxel, or alternatively the same voxel as another cell.

Add a voxel index to the CellList class

---

simulation/cell.py
simulation/coordinates.py
simulation/grid.py
test/test_cell.py
test/test_grid.py
tox.ini

@jmasison01 This is meant to replace some of the logic in your modules where you are iterating over voxels near a point.
There is one difference in `get_adjecent_voxels` that we may need to go over.  In this implementation, I only return the six voxels that share a size rather than all 26 that touch on edges and corners as you are using in your code.  
I did this because it is more common in numerical simulations.  You are often modelling the flux between grid cells--those that don't share a side have no flux.  An alternative approach is to generate an empirical diffusion that will spread a quantity over some volume.  This would be appropriate in cases where the time steps are large.  In this case, you would want to use something like the `get_voxels_in_range` method.
It's simple to …

Add methods on the grid to get neighboring voxels

---

simulation/diffusion.py
test/test_diffusion.py

The intended use case for this code is to perform "surface diffusion"
generated by a mask from the `lung_tissue` variable, e.g.
```python
surface_mask = lung_tissue == TissueTypes.EPITHELIUM
laplacian = discrete_laplacian(grid, mask)
iron_concentration[:] = apply_diffusion(iron_concentration, laplacian,
diffusivity, dt)
```
Computation of the laplacian matrix is slow for the pure python
implementation (10-15 seconds on the reference grid).  It is expected we
will precompute it during the geometry initialization, and include it
in the geometry file.

Add methods to perform diffusion on masked fields

---

simulation/modules/afumigatus.py
simulation/modules/epithelium.py
simulation/modules/fungus.py
simulation/modules/macrophage.py
simulation/modules/neutrophil.py
simulation/modules/phagocyte.py
simulation/random.py

This removes the use of Python's `random` module and NumPy's legacy `RandomState`. Instead, all random numbers are generated from a single, application-wide NumPy `Generator` instance.
Python's `random` module can't always be used, because it can't provide all of the array-valued outputs as NumPy. Since the simulation has to use NumPy for some RNG, it should use it for all RNG. This ensures that the seed is managed in only one place and that the various APIs are easy to directly compare.
NumPy's documentation discourages the use of `np.random...`, as this uses the legacy `RandomState` interface. Instead, they recommend instantiating a `Generator` instance and using it for all RNG: https://numpy.org/doc/1.18/reference/random/generator.html
For now, the new Generator is seeded with random …

Switch all RNG to use a global Generator instance

---

simulation/modules/afumigatus.py

Iterator is essentially a subset of Iterable. In parameter types, we should be maximally permissive. In return types, we should be maximally descriptive.

Annotate a generator return with the stronger Iterator type

---

simulation/cli.py
simulation/solver.py

This is necessary to distinguish between the different phases of the simulation without having to infer the status from time step information.

Add a status enum returned with run_iterator

---

README.md
nlisim/config.py
nlisim/module.py
nlisim/modules/afumigatus.py
nlisim/modules/epithelium.py
nlisim/modules/fungus.py
nlisim/modules/geometry.py
nlisim/modules/macrophage.py
nlisim/modules/molecules.py
nlisim/modules/neutrophil.py
nlisim/modules/plot.py
nlisim/modules/state_output.py
nlisim/modules/visualization.py
nlisim/solver.py
test/test_config.py

when a module is both the model and state. Rename Module class to ModuleModel, mirroring ModuleState

Having a class called Module is confusing

---

README.md

There's no need to indent code blocks, and it makes copy-pasting more difficult.

Clean up indentation in README

---

Dockerfile
config.ini.example
nlisim/modules/geometry.py
nlisim/modules/visualization.py
nlisim/postprocess.py

This also removes the `Geometry` module's `preview_geometry` code, which was unmaintained. If this feature is desired in the future, it should be implemented as a separate CLI sub-command, and run outside the scope of a `ModuleModel`.

Remove OpenGL dependency on vtk import

---

nlisim/cell.py
nlisim/cli.py
nlisim/config.py
nlisim/modules/afumigatus.py
nlisim/modules/epithelium.py
nlisim/modules/geometry.py
nlisim/molecule.py
nlisim/state.py
nlisim/validation.py
pyproject.toml
test/test_afumigatus.py
test/test_epithelium.py
test/test_fungus.py
test/test_macrophage.py
test/test_neutrophil.py
test/test_validator.py
tox.ini

This has the major benefit of automatically sorting imports on behalf of the developer, during `tox -e format`, as opposed to `flake8-import-order` which requires manual resolution every time.

Use isort for import ordering

---

.circleci/config.yml
setup.py
tox.ini

This now does the release build cleanly within Tox. It also updates the environment variables in `prerelease_local_scheme` to those used by CircleCI.

Clean up the release process

---

Dockerfile

This reduces the total image size from 995MB to 636MB (36%).

Use a multi-stage Docker build

---

.circleci/config.yml
Dockerfile
Pipfile
Pipfile.lock
pyproject.toml
setup.py

This is the default Python installed by both Ubuntu 18.04 and 20.04. Standardizing around this version will significantly simplify testing and support. Now that a Docker build is published, it's also possible for downstream users without access to the correct Python version to run the simulation regardless.

Require Python 3.8

---

nlisim/cli.py

This allows invocation of `python nlisim/cli.py` directly, without necessarily using the installed entry point.

Allow the cli to be run directly from a file

---

.circleci/config.yml
Pipfile.lock
setup.py

This reverts part of #95 because the infrastructure of https://data.nutritionallungimmunity.org/ runs on python 3.6.  We can revert this after that gets updated, but it would be a significant amount of work to do just for this.

Allow installation on python 3.6

---

config.ini
nlisim/module.py
nlisim/modules/epithelium.py
nlisim/modules/fungus.py
nlisim/modules/macrophage.py
nlisim/modules/molecules.py
nlisim/modules/neutrophil.py

json serialization requires that all floats are standard python float's, not e.g. numpy.float32's

Summary stats
