NutritionalLungImmunity/nlisim

.circleci/config.yml, tox.ini
@brianhelba This will need someone with admin access to enable CI integraiton.
=> Add a circleci config for testing

.gitignore, config.ini.example, config.ini.unstable, setup.py, simulation/config.py, simulation/module.py, simulation/modules/save.py, simulation/state.py
=> Implement HDF5 based serialization

Pipfile.lock
=> Regenerate lockfile to bring in latest dependencies

simulation/cell.py, test/test_afumigatus.py
Fixes #18
@EricMei542 Note the changes I made to your test cases.  I believe the logic is now correct.
=> Fix logic in cell tree growth and branching

tox.ini
Ref: https://github.com/PyCQA/pydocstyle/issues/434
=> Pin pydocstyle to work around a bug

simulation/modules/afumigatus.py, test/test_afumigatus.py
This change also resolves a TODO in the code by making it clear that the
afumigatus cell tree class **actually** represents multiple trees.  This
is made explicit by renaming the class to `AfumigatusCellTreeList` and
fixing the `roots` property to return **all** root cells.
=> Implement killable cells in the afumigatus cell tree

tox.ini
The issue has been fixed upstream.
=> Remove pinned pydocstyle

.circleci/config.yml, .gitignore, simulation/__init__.py, tox.ini
Automatically publishes the docs to <http://nutritionallungimmunity.github.io/simulation-framework>.
=> Publish documentation in CI

simulation/grid.py, test/test_grid.py
This is just some code ported from another branch I'm working on.  It may come in handy for others.
=> Add additional methods to help with grid/voxel interaction

simulation/modules/macrophage.py, simulation/modules/phagocyte.py
Filled in implementation of 'update' function, so that over time the status of a macrophage changes according to previous status.
=> added status change

config.ini.example, simulation/modules/fungus.py, simulation/modules/macrophage.py, simulation/modules/neutrophil.py, test/test_macrophage.py
Macrophage module unit tests added and bugs fixed. Minor changes to fungus module to reflect oremland model more closely.
=> Macrophage oremland

simulation/modules/epithelium.py, simulation/modules/macrophage.py, test/test_epithelium.py, test/test_macrophage.py
Tested and fixed bugs in the epithelium module
=> Epi oremland

simulation/modules/neutrophil.py, test/test_neutrophil.py
=> age neutrophil and age limit

simulation/modules/molecules.py, simulation/modules/neutrophil.py, test/test_macrophage.py, test/test_molecules.py
Cytokine and iron implementation and diffusion
=> Cytokine oremland

config.ini.example, simulation/modules/fungus.py, test/test_fungus.py
add configurable parameters for time for the fungus cells to change status from resting and from swollen.
=> fungal time dependent status change

simulation/modules/epithelium.py, simulation/modules/macrophage.py, test/test_epithelium.py, test/test_macrophage.py
Fixed logic error in spore internalization and added configurable parameter for probability of internalization
=> Oremland fix internalize

simulation/cli.py, simulation/module.py, simulation/modules/fungus.py, simulation/modules/macrophage.py, simulation/modules/neutrophil.py, simulation/plot.py, simulation/solver.py
Implementation of cells & cost plotting.
=> Oremland plot cells

simulation/modules/molecules.py, test/test_molecules.py
Optimization of diffusion with convolution
=> Oremland diffusion opt

.editorconfig, .gitattributes
This will help to prevent common indentation and line ending problems.
=> Add editorconfig and gitattributes files

.circleci/config.yml, README.md, tox.ini
This may be easier to review looking at individual commits.
=> Update README documentation

Pipfile.lock, setup.py, simulation/cli.py, simulation/config.py, simulation/state.py, test/conftest.py, test/test_afumigatus.py, test/test_config.py
This may be easier to review looking at individual commits.
=> Improve config file loading

Pipfile, Pipfile.lock
This supersedes #69. It does not remove anything.
=> Update Pipfile.lock and add Jupyter

simulation/cli.py, simulation/postprocess.py
This should be easier to expand with additional postprocessing functionality.
Postprocess now also clears its postprocess output directory before each run.
Also, add typing to CLI functions.
=> Refactor postprocess

README.md, config.ini.example, nlisim/config.py, nlisim/module.py, nlisim/modules/epithelium.py, nlisim/modules/fungus.py, nlisim/modules/geometry.py, nlisim/modules/macrophage.py, nlisim/modules/neutrophil.py, nlisim/modules/state_output.py, nlisim/modules/visualization.py, test/conftest.py, test/test_afumigatus.py, test/test_config.py
Defaults go against the 'all parameters are in the configuration file' principle. These changes move toward eliminating them.
=> Destroy all defaults

config.ini, config.ini.example, nlisim/modules/epithelium.py, nlisim/modules/macrophage.py, nlisim/modules/molecules.py, nlisim/modules/neutrophil.py, nlisim/modules/visualization.py, test/test_macrophage.py, test/test_neutrophil.py
Also, the "print to stdout" feature is now a "write to csv" feature
=> fix array indexing issue affecting macrophage/neutrophil recruitment

nlisim/modules/epithelium.py, nlisim/modules/macrophage.py, nlisim/modules/neutrophil.py, test/test_neutrophil.py
As part of a mini-project to understand why macrophages were ending up in air voxels, I have simplified a number of loops.
=> Loop simplification and randomization

nlisim/postprocess.py
So we can't mutate the tissue array. Adding in a copy. If the geometry ever gets big, this should be reconsidered.
=> postprocessing can sometimes occur in memory

config.ini.example
visualization module now requires that the molecules plugin is loaded first
=> Summary stats

config.ini, nlisim/modules/afumigatus.py, nlisim/modules/il10.py, nlisim/modules/lactoferrin.py, nlisim/modules/macrophage.py, nlisim/modules/neutrophil.py, nlisim/modules/phagocyte.py, nlisim/modules/pneumocyte.py, nlisim/solver.py
randomize run order for concurrent modules, remove unused modules from config.ini, various fixes
=> cleanup and bug fix

.circleci/config.yml, setup.py
update docker image and circleCI config to reflect the current requirements
=> Circleci update

nlisim/modules/transferrin.py
ensure that transferrin is not placed in air voxels
=> Transferrin out of air
